apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ingress-merge.fullname" . }}
  labels:
    app: {{ include "ingress-merge.name" . }}
    chart: {{ include "ingress-merge.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  annotations: |
  {{.Values.annotations | indent 4 }}
