# Ingress-class annotation to manage
ingressClass: merge

# Label selector for ConfigMap objects to be monitored for changes
# e.g. "merge.ingress.kubernetes.io=owned"
configMapSelector: ""

# Label selector for Ingress objects to be monitored for changes
ingressSelector: ""

# List of annotations that will cause a ConfigMap to be ignored if present
# e.g. "control-plane.alpha.kubernetes.io/leader"
configMapWatchIgnore: []

# List of annotations that will cause an Ingress to be ignored if present
ingressWatchIgnore: []

rbac:
  create: true
  serviceAccountName: default

image:
  repository: ponomarevkonst/public:ingress-merge
  tag: latest
  pullPolicy: Always

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
